host "192.168.100.49:8080" {
    proxy_pass http://192.168.100.49:8000;
    proxy_pass http://192.168.100.49:8001;
    dist_policy round-robin;
}

host "app1.local" {
    proxy_pass http://192.168.100.49:9001;
}

host "app2.local" {
    proxy_set_header Host $host;

    proxy_pass http://192.168.100.49:9002;
    proxy_pass http://192.168.100.49:9003;

    dist_policy round-robin;
}
